apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-squared-resources
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: OCIRepository
    name: gitops-squared-catalog
  path: ./manifests
  prune: true
  wait: true
  timeout: 1m
